---
title: "Exams"
---

Three take-home exams will be given during the term, and will be made available on a Friday, to be completed before class the following Monday. Tentatively, the first is scheduled for Friday, September 25th (Week 4), the second for Friday, October 23 (Week 8), and the third for November 13th (Week 11). The exams are intended to take between 3 and 4 hours to complete.

## Exam 1

### Logistics

1. The exam will cover material from Chapter 2 and Chapter 3 of ISLR.

2. The exam will be made available on GitHub at 3pm PDT on Friday, 9-25. A link to the exam will be posted in the #announcements channel on Slack.

3. You must submit your completed exam via pushing any commits to GitHub prior to the start of class on Monday, 9-28.

4. This is a timed exam. You should schedule 3 consecutive hours to work on the exam sometime between Friday and Monday. **Once you accept the assignment by following the GitHub link and creating your exam repo, you must submit your exam by pushing commits within the following 3 hours**. A cumulative 5% grade penalty will be applied for every 10 minutes you exceed this time limit.


5. You may freely consult the following references during the exam:
  - Your ISLR textbook
  - Any course notes you have taken
  - Lecture slides on the course website
  - Homework problems you have submitted
  - Built-in RStudio help files and cheatsheets
  
6. You may not consult any other resources, including (but not limited to):
  - Classmates
  - Tutors
  - Other faculty
  - Other textbooks
  - Online help (stackexchange, message boards, etc.)
  
  
7. I will be available to troubleshoot and answer technical questions from noon to 5pm PDT on Sunday. If you run into problems outside of this time frame, document the problem in your exam and message me on slack. I will try to respond as soon as I can, but can't guarantee I will available at that moment. In any case, be sure to submit within 3 hours of accepting the assignment. If the problem is severe enough, we may discuss alternatives.
