---
title: "Schedule"
---

## Week 1

### Monday 8-31


[Lecture Slides](lectures/8-31_Intro.pdf)

#### Topics

- Course Logistics
- How old am I?
  - [Class data](data/how_old.csv) *Groups 1 - 6 were student groups, Group 7 estimates came from [how-old.net](https://how-old.net) and Group 8 are my estimates based on public data*

#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Review the syllabus

#### Due


- Complete Slack Introduction:
  1. Sign-in to our [Slack workspace](reedmath243fall2020.slack.com)
  2. Navigate to the #general-discussion channel using the menu on the left side of the screen and post a message with your name and three numeric values that describe yourself, two of which are true and one of which is false (don't say which is which).
  3. Find another person's post, hover over it, and click the chat bubble icon to start a thread. Then guess which of that person's three statements is false.
  4. Finally, find my name (Nate Wells) under Direct Messages on the left side of the screen, and send me a private message answering the following questions:
      a) What is your preferred name? (and what are your pronouns, if you'd like to share?)
      b) Do you have experience using R and Rstudio?
      c) What do you hope to take away from this course?
      d) What concerns do you have about this course, or about academics in general this term?
      e) What is one image that best describes you? (feel free to upload it) 




### Wednesday 9-2

[Lecture Slides](lectures/9-2_GitHub.pdf)

#### Topics

- RStudio

- GitHub
  - [Working Solo](https://github.com/Reed-Stat-Learning-Fall-2020/course-materials/raw/master/Activities/working_solo_github.pdf)

- GitHub Classroom

#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Chapter 1 and Section 2.1 (p 1-29) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

- [Chapter 1](https://happygitwithr.com/big-picture.html) and [Chapter 4](https://happygitwithr.com/github-acct.html) in [Happy Git and GitHub for the useR](https://happygitwithr.com/)

#### Due

- Sign up for a [GitHub](https://github.com) account.

### Friday 9-4

[Lecture Slides](lectures/9-4_Estimating_f.pdf)


#### Topics

- Estimating $f$, the relationship between predictor and response variables

- Assessing error in the guess my age activity


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Review Section 2.1 (p 15-29) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

#### Due

- Homework 0. (Use the link in the #announcments channel to create your repo and view the assignment. Make sure you push any commits you make before 1:35pm on Friday.)


***********************************************



## Week 2

### Monday 9-7

No class; Labor Day



### Wednesday 9-9

[Lecture Slides](lectures/9-9_Assessing_Accuracy.pdf)

#### Topics

- Decomposing the Mean Squared Error
  
  - [Wednesday 9-9 Demo](files/demo_9-9.Rmd)

- The Bias-Variance Trade-off


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 2.2 (p 29-41) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

#### Assigned

- Homework 1 (Due Wednesday, 9/16 by the start of class)



### Friday 9-11

[Lecture Slides](lectures/9-11_SLR.pdf)

#### Topics

- Review Simple Linear Regression

- Introduction to Multiple Linear Regression


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 3.1 (p 59-72) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)





**************************************************




## Week 3

### Monday 9-14

[Lecture Slides](lectures/9-14_MLR.pdf)

#### Topics
 

- Introduction to Multiple Linear Regression
  - [Regression plane for MLR](files/3d_scatterplot.html) [(.Rmd)](files/3d_scatterplot.Rmd)
- Assessing Accuracy of Linear Models
- Linear Models in R
  


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 3.2 (p 71-82) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

### Wednesday 9-16

[Lecture Slides](lectures/9-16_MLR_Accuracy.pdf)

#### Topics
 

- Extensions of the Linear Model


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 3.3 (p 82-92) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

#### Due

- Homework 1


#### Assigned

- Homework 2, To be posted by Wed. evening (Due Wednesday, 9/23 by the start of class)


### Friday 9-18

[Lecture Slides](lectures/9-18_MLR_Extensions.pdf)

#### Topics
 

- Extensions of the Linear Model
  - [Code from today's class](files/Demo_9-18.Rmd)


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 3.3 (p 92-102) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)


**********************************************

## Week 4

### Monday 9-21

[Lecture Slides](lectures/9-21_MLR_Troubleshooting.pdf)

[Lecture Video](https://ensemble.reed.edu/Watch/t6MQf3q4) (requires Reed Kerberus credentials to watch)

#### Topics
 

- Troubleshooting linear models
  


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 3.6 (p 109-119) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

### Wednesday 9-23
 [Lecture Slides](lectures/9-23_MLR_Examples.pdf)
 
 [Lecture Video](https://ensemble.reed.edu/Watch/Ec79MyRr) (requires Reed Kerberus credentials to watch)

#### Topics
 

- Transformations


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 3.5 (p 104-109) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

#### Due

- Homework 2


#### Assigned

- No homework assigned.


### Friday 9-25


[Lecture Video](https://ensemble.reed.edu/Watch/Kp64Czj9)

#### Topics
 

- Review
  - [Midterm Practice](files/Midterm_1_Review.Rmd)

#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- None

**********************************************

## Week 5

### Monday 9-28

[Lecture Slides](lectures/9-28_KNN.pdf)  

#### Topics
 

- KNN and Bayes Classifier
  
  - [Classification Activity](files/classification.Rmd)

#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Review Section 2.2.3 (p 37-42) and Section 3.5 (p 104-109) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)



### Wednesday 9-30
 

#### Topics
 

- Logistic Regression


#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 4.1 - 4.3 (p 127-137) and Section 4.6.2 (p 156 - 160) in [Introduction to Statistical Learning](http://faculty.marshall.usc.edu/gareth-james/ISL/)

#### Due

- None


#### Assigned

- HW 3 assigned (Due Wednesday 10/7 by 1:35pm)


### Friday 9-25



#### Topics
 

-  More Logistic Regression 

#### Reading Assignment

*Note that the listed reading assignments should be completed prior to class*

- Section 12.1 - 12.2 (p 275 - 287) in [Applied Predictive Modeling](https://link-springer-com.proxy.library.reed.edu/book/10.1007%2F978-1-4614-6849-3) 